much better FORCE_UPDATE ability in start

diff --git a/src/www/code/start b/src/www/code/start
--- a/src/www/code/start
+++ b/src/www/code/start
@@ -19,34 +19,56 @@ fi                                                        #
 ###########################################################
 
 
-# Auto-download other files:
-for x in README.txt run stop recursive_mount mount_host umount_host; do
-    if [ ! -f "$MYDIR/$x" ]; then
-        wget -q -O "$MYDIR/.downloading" "http://nomake.org/code/$x";
-        mv "$MYDIR/.downloading" "$MYDIR/$x"
-        if [ "$x" != "README.txt" ]; then
-            chmod a+x "$MYDIR/$x"
-        fi
+### Updates and Downloads: ###
+function download {
+    fname="$1"
+    echo "Downloading ${fname}..."
+    wget -q -O "$MYDIR/.downloading" "http://nomake.org/code/$fname?nocache=$(date '+%s')";
+    result=$?
+    if [ "$result" != 0 ]; then return $result; fi
+    mv "$MYDIR/.downloading" "$MYDIR/$fname"
+    if [ "$fname" != "README.txt" ]; then chmod a+x "$MYDIR/$fname"; fi
+    return 0
+}
+if [ "${FORCE_UPDATE:-0}" = 1 ]; then
+    download start
+    result=$?
+    if [ "$result" != 0 ]; then
+        echo 'Update Failed!  Aborting.'
+        exit 1
     fi
+    for x in README.txt run stop recursive_mount mount_host umount_host; do #### S
+        if [ -f "$MYDIR/$x" ]; then mv "$MYDIR/$x" "$MYDIR/.${x}_old"; fi      # A
+    done                                                                       # M
+    FORCE_UPDATE=0 "$MYDIR/start"   # Re-launch new version.                   # EF
+    result=$?                                                                  #  I
+    exit $result                                                               #  L
+fi                                                                             #  E
+for x in README.txt run stop recursive_mount mount_host umount_host; do ########  S
+    if [ ! -f "$MYDIR/$x" ]; then download "$x"; fi
 done
 
-# Make the 'RUNNING' file:
+
+### Make the 'RUNNING' file: ###
 touch "$RUNNING_FILE"
 chmod 777 "$RUNNING_FILE"  # For colors in LS listings.
 
-# Core mounts:
+
+### Core mounts: ###
 "$MYDIR/recursive_mount" mount /dev "$CHROOT_DIR/dev"
 "$MYDIR/recursive_mount" mount /proc "$CHROOT_DIR/proc"
 "$MYDIR/recursive_mount" mount /sys "$CHROOT_DIR/sys"
 "$MYDIR/recursive_mount" mount /tmp "$CHROOT_DIR/tmp"
 
-# Host mounts:
+
+### Host mounts: ###
 if [ "${MOUNT_HOST:-0}" = 1 ]; then
     ./mount_host
 fi
 
-# Boot script:
-if [ "$IS_RUNNING" = 0 ]; then
+
+### Boot script: ###
+if [ "$IS_RUNNING" = 0  -o  "${FORCE_BOOT:-0}" = 1 ]; then
     "$MYDIR/run" /nomake/boot.sh
 else
     echo 'Already started.'
diff --git a/src/www/code/stop b/src/www/code/stop
--- a/src/www/code/stop
+++ b/src/www/code/stop
@@ -19,16 +19,34 @@ fi                                                        #
 ###########################################################
 
 
+ANY_ERRORS=0
+
 "$MYDIR/run" /nomake/halt.sh
+result=$?
+if [ "$result" != 0 ]; then
+    echo 'Error in halt.sh.'
+    ANY_ERRORS=1
+fi
 
 "$MYDIR/umount_host"
+result=$?; if [ "$result" != 0 ]; then ANY_ERRORS=1; fi
 
 "$MYDIR/recursive_mount" umount "$CHROOT_DIR/tmp"
+result=$?; if [ "$result" != 0 ]; then ANY_ERRORS=1; fi
 "$MYDIR/recursive_mount" umount "$CHROOT_DIR/sys"
+result=$?; if [ "$result" != 0 ]; then ANY_ERRORS=1; fi
 "$MYDIR/recursive_mount" umount "$CHROOT_DIR/proc"
+result=$?; if [ "$result" != 0 ]; then ANY_ERRORS=1; fi
 "$MYDIR/recursive_mount" umount "$CHROOT_DIR/dev"
+result=$?; if [ "$result" != 0 ]; then ANY_ERRORS=1; fi
+
 
 # In case the user mounted anything extra:
 "$MYDIR/recursive_mount" umount "$CHROOT_DIR"
+result=$?; if [ "$result" != 0 ]; then ANY_ERRORS=1; fi
 
-rm "$RUNNING_FILE" 2>/dev/null
+if [ "$ANY_ERRORS" = 0 ]; then
+    rm "$RUNNING_FILE" 2>/dev/null
+fi
+
+exit $ANY_ERRORS
